#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(ggplot2)
})

# This script starts from filtered all-data pseudobulk Seurat objects generated by
# pseudobulking_qc_pbsample.R, then reruns PCA/covariate association within each
# remaining cell-type subset.

BASE_FIG_DIR  <- "/quobyte/lasallegrp/Osman/shenyu/03_figures/deg/sample_level_view/qc"
BASE_FILE_DIR <- "/quobyte/lasallegrp/Osman/shenyu/04_results/deg/sample_level_view/qc"

CLUSTER_RESOLUTIONS <- c("neuron_class", "cell_type_concise")

N_PCS_ASSOC <- 5
N_PCS_VAR   <- 30

BASE_PCA_COVARIATES <- c(
  "sample",
  "animal_genotype",
  "animal_sex",
  "animal_timepoint",
  "psbulk_cells",
  "psbulk_cells_log",
  "psbulk_counts",
  "psbulk_counts_log"
)

safe_name <- function(x) {
  x <- as.character(x)
  x <- gsub("[^A-Za-z0-9]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  ifelse(nchar(x) == 0, "unknown", x)
}

get_available_npcs <- function(object, requested_npcs) {
  max_npcs <- min(ncol(object) - 1, nrow(object) - 1)
  max(0, min(requested_npcs, max_npcs))
}

preprocess_subset_pca <- function(seurat_pb_subset, n_pcs = N_PCS_VAR) {
  DefaultAssay(seurat_pb_subset) <- "RNA"
  n_pcs <- get_available_npcs(seurat_pb_subset, n_pcs)

  if (n_pcs < 2) {
    return(NULL)
  }

  seurat_pb_subset <- NormalizeData(
    seurat_pb_subset,
    normalization.method = "LogNormalize",
    scale.factor = 1e6,
    verbose = FALSE
  )
  seurat_pb_subset <- FindVariableFeatures(seurat_pb_subset, verbose = FALSE)
  seurat_pb_subset <- ScaleData(seurat_pb_subset, verbose = FALSE)
  seurat_pb_subset <- RunPCA(seurat_pb_subset, npcs = n_pcs, verbose = FALSE)
  seurat_pb_subset
}

check_metadata_pca <- function(object,
                               reduction = "pca",
                               n_pcs = N_PCS_ASSOC,
                               covariates) {
  pcs <- Embeddings(object, reduction = reduction)
  n_pcs <- min(n_pcs, ncol(pcs))
  pcs <- pcs[, seq_len(n_pcs), drop = FALSE]
  meta <- object[[]]
  covariates <- intersect(covariates, colnames(meta))

  expand.grid(
    covariate = covariates,
    PC = colnames(pcs),
    stringsAsFactors = FALSE
  ) %>%
    rowwise() %>%
    mutate(
      p_value = {
        y <- pcs[, PC]
        x <- meta[[covariate]]
        keep <- !is.na(y) & !is.na(x)
        y <- y[keep]
        x <- x[keep]
        if (length(unique(x)) < 2 || length(y) < 3) {
          NA_real_
        } else if (is.numeric(x)) {
          summary(lm(y ~ x))$coefficients[2, 4]
        } else {
          fit <- anova(lm(y ~ factor(x)))
          fit[1, "Pr(>F)"]
        }
      },
      score = {
        y <- pcs[, PC]
        x <- meta[[covariate]]
        keep <- !is.na(y) & !is.na(x)
        y <- y[keep]
        x <- x[keep]
        if (length(unique(x)) < 2 || length(y) < 3) {
          NA_real_
        } else if (is.numeric(x)) {
          suppressWarnings(cor(y, x, method = "spearman"))
        } else {
          fit <- anova(lm(y ~ factor(x)))
          as.numeric(fit[1, "F value"])
        }
      },
      variable_type = ifelse(is.numeric(meta[[covariate]]), "numeric", "categorical")
    ) %>%
    ungroup() %>%
    mutate(
      p_adj = p.adjust(p_value, method = "BH"),
      neg_log10_padj = -log10(pmax(p_adj, .Machine$double.xmin))
    )
}

plot_metadata_pca <- function(pca_assoc, title, padj_cutoff = 0.05) {
  sig_assoc <- pca_assoc %>% filter(!is.na(p_adj), p_adj < padj_cutoff)

  p <- ggplot(pca_assoc, aes(x = PC, y = covariate, fill = neg_log10_padj)) +
    geom_tile(color = "white") +
    scale_fill_gradient(
      low = "#F7F7F7",
      high = "#4B0082",
      na.value = "grey90",
      name = expression(-log[10] ~ "(padj)")
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid = element_blank()
    ) +
    labs(
      x = "Principal component",
      y = "Metadata covariate",
      title = title
    )

  if (nrow(sig_assoc) > 0) {
    p <- p +
      geom_point(
        data = sig_assoc,
        aes(x = PC, y = covariate, shape = "padj < 0.05", color = "padj < 0.05"),
        inherit.aes = FALSE,
        size = 2.1,
        stroke = 0.8
      ) +
      scale_shape_manual(name = NULL, values = c("padj < 0.05" = 8)) +
      scale_color_manual(name = NULL, values = c("padj < 0.05" = "red")) +
      guides(
        shape = guide_legend(override.aes = list(color = "red", size = 3)),
        color = "none"
      )
  }

  p
}

plot_pca_variance_rank <- function(object, reduction = "pca", n_pcs = N_PCS_VAR) {
  stdev <- object[[reduction]]@stdev
  n_pcs <- min(n_pcs, length(stdev))
  pct <- stdev^2 / sum(stdev^2)

  data.frame(
    ranking = seq_len(n_pcs),
    PC = paste0("PC", seq_len(n_pcs)),
    variance = pct[seq_len(n_pcs)]
  ) %>%
    ggplot(aes(x = ranking, y = variance, label = PC)) +
    geom_col(width = 0.7, fill = "grey75") +
    geom_text(angle = 90, hjust = -0.1, size = 3) +
    theme_bw() +
    labs(x = "ranking", y = "variance explained", title = "PCA variance explained")
}

save_pca_covariate_plots <- function(object,
                                     covariates,
                                     out_path,
                                     title_prefix,
                                     reduction = "pca") {
  coords <- as.data.frame(Embeddings(object, reduction = reduction)[, 1:2, drop = FALSE])
  colnames(coords) <- c("PC1", "PC2")
  meta <- object[[]]
  covariates <- intersect(covariates, colnames(meta))

  pdf(out_path, width = 10, height = 8)
  for (covariate in covariates) {
    plot_df <- bind_cols(coords, value = meta[[covariate]])
    p <- ggplot(plot_df, aes(x = PC1, y = PC2, color = value)) +
      geom_point(size = 2.2, alpha = 0.9) +
      theme_bw() +
      labs(title = paste(title_prefix, covariate, sep = " - "), color = covariate)

    if (is.numeric(plot_df$value)) {
      p <- p + scale_color_viridis_c(option = "viridis", direction = 1)
    } else {
      plot_df$value <- as.factor(plot_df$value)
      p <- ggplot(plot_df, aes(x = PC1, y = PC2, color = value)) +
        geom_point(size = 2.2, alpha = 0.9) +
        theme_bw() +
        labs(title = paste(title_prefix, covariate, sep = " - "), color = covariate)
    }
    print(p)
  }
  dev.off()
}

run_subset_exploratory_analysis <- function(seurat_pb,
                                            cluster_resolution,
                                            subset_level,
                                            fig_dir,
                                            n_pcs_assoc = N_PCS_ASSOC,
                                            n_pcs_var = N_PCS_VAR,
                                            covariates = BASE_PCA_COVARIATES) {
  subset_safe <- safe_name(subset_level)
  subset_dir <- file.path(fig_dir, subset_safe)
  dir.create(subset_dir, recursive = TRUE, showWarnings = FALSE)

  seurat_subset <- subset(
    seurat_pb,
    cells = colnames(seurat_pb)[as.character(seurat_pb[[cluster_resolution]][, 1]) == subset_level]
  )

  message("  ", subset_level, ": ", ncol(seurat_subset), " pseudobulk samples")

  seurat_subset <- preprocess_subset_pca(seurat_subset, n_pcs = n_pcs_var)
  if (is.null(seurat_subset)) {
    message("    Skipped: fewer than 3 pseudobulk samples or features.")
    return(NULL)
  }

  covariates <- setdiff(covariates, cluster_resolution)
  covariates <- intersect(covariates, colnames(seurat_subset[[]]))

  pca_assoc <- check_metadata_pca(
    object = seurat_subset,
    reduction = "pca",
    n_pcs = n_pcs_assoc,
    covariates = covariates
  )

  assoc_csv <- file.path(subset_dir, paste0("pca_metadata_assoc_", subset_safe, ".csv"))
  write.csv(pca_assoc, assoc_csv, row.names = FALSE)

  p <- plot_metadata_pca(
    pca_assoc,
    title = paste(cluster_resolution, subset_level, "PCA metadata association", sep = " - ")
  )
  ggsave(
    file.path(subset_dir, paste0("pca_metadata_assoc_", subset_safe, ".pdf")),
    plot = p,
    height = 5.5,
    width = 8
  )

  p <- plot_pca_variance_rank(seurat_subset, n_pcs = n_pcs_var)
  ggsave(
    file.path(subset_dir, paste0("pca_variance_", subset_safe, ".pdf")),
    plot = p,
    height = 4,
    width = 7
  )

  save_pca_covariate_plots(
    object = seurat_subset,
    covariates = covariates,
    out_path = file.path(subset_dir, paste0("pca_covariates_", subset_safe, ".pdf")),
    title_prefix = paste(cluster_resolution, subset_level, sep = " - ")
  )

  invisible(seurat_subset)
}

process_cluster_resolution <- function(cluster_resolution) {
  message("Processing cluster resolution: ", cluster_resolution)

  object_path <- file.path(
    BASE_FILE_DIR,
    paste0("pseudobulk_seurat_", cluster_resolution, ".rds")
  )
  if (!file.exists(object_path)) {
    stop("Filtered pseudobulk Seurat object not found: ", object_path)
  }

  fig_dir <- file.path(BASE_FIG_DIR, cluster_resolution)
  dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)

  seurat_pb <- readRDS(object_path)
  if (!cluster_resolution %in% colnames(seurat_pb[[]])) {
    stop("Metadata column not found in pseudobulk object: ", cluster_resolution)
  }

  subset_levels <- seurat_pb[[]] %>%
    count(.data[[cluster_resolution]], name = "n_pseudobulk_samples") %>%
    arrange(desc(n_pseudobulk_samples), .data[[cluster_resolution]])

  for (subset_level in as.character(subset_levels[[cluster_resolution]])) {
    run_subset_exploratory_analysis(
      seurat_pb = seurat_pb,
      cluster_resolution = cluster_resolution,
      subset_level = subset_level,
      fig_dir = fig_dir
    )
  }

  invisible(subset_levels)
}

invisible(lapply(CLUSTER_RESOLUTIONS, process_cluster_resolution))
